// Listen to item tag event
onEvent('tags.items', event => {

  event.removeAllTagsFrom('boss_tools:steel_block')
  event.removeAllTagsFrom('boss_tools:steel_ingot')

  event.removeAllTagsFrom('bloodmagic:coalsand')
  event.removeAllTagsFrom('createaddition:diamond_grit')
  event.removeAllTagsFrom('mekanism:dust_diamond')
  event.removeAllTagsFrom('boss_tools:steel_ingot')
  
    event.removeAllTagsFrom('create:copper_ingot')
    event.removeAllTagsFrom('forestry:ingot_copper')
    event.removeAllTagsFrom('immersiveengineering:ingot_copper')
    event.removeAllTagsFrom('mekanism:ingot_copper')
    event.removeAllTagsFrom('occultism:copper_ingot')
    event.removeAllTagsFrom('projectred-core:copper_ingot')
    event.removeAllTagsFrom('tconstruct:copper_ingot')
    event.removeAllTagsFrom('cavesandcliffs:copper_ingot')
    event.removeAllTagsFrom('tmechworks:copper_ingot')

    event.removeAllTagsFrom('create:tin_ingot')
    event.removeAllTagsFrom('forestry:ingot_tin')
    event.removeAllTagsFrom('immersiveengineering:ingot_tin')
    event.removeAllTagsFrom('mekanism:ingot_tin')
    event.removeAllTagsFrom('occultism:tin_ingot')
    event.removeAllTagsFrom('projectred-core:tin_ingot')
    event.removeAllTagsFrom('tconstruct:tin_ingot')
    event.removeAllTagsFrom('cavesandcliffs:tin_ingot')
    event.removeAllTagsFrom('tmechworks:tin_ingot')

    event.removeAllTagsFrom('create:lead_ingot')
    event.removeAllTagsFrom('forestry:ingot_lead')
    event.removeAllTagsFrom('immersiveengineering:ingot_lead')
    event.removeAllTagsFrom('mekanism:ingot_lead')
    event.removeAllTagsFrom('occultism:lead_ingot')
    event.removeAllTagsFrom('projectred-core:lead_ingot')
    event.removeAllTagsFrom('tconstruct:lead_ingot')
    event.removeAllTagsFrom('cavesandcliffs:lead_ingot')
    event.removeAllTagsFrom('tmechworks:lead_ingot')

    event.removeAllTagsFrom('create:silver_ingot')
    event.removeAllTagsFrom('forestry:ingot_silver')
    event.removeAllTagsFrom('immersiveengineering:ingot_silver')
    event.removeAllTagsFrom('mekanism:ingot_silver')
    event.removeAllTagsFrom('occultism:silver_ingot')
    event.removeAllTagsFrom('projectred-core:silver_ingot')
    event.removeAllTagsFrom('tconstruct:silver_ingot')
    event.removeAllTagsFrom('cavesandcliffs:silver_ingot')
    event.removeAllTagsFrom('tmechworks:silver_ingot')

    event.removeAllTagsFrom('create:nickel_ingot')
  event.removeAllTagsFrom('forestry:ingot_nickel')
  event.removeAllTagsFrom('immersiveengineering:ingot_nickel')
  event.removeAllTagsFrom('mekanism:ingot_nickel')
  event.removeAllTagsFrom('occultism:nickel_ingot')
  event.removeAllTagsFrom('projectred-core:nickel_ingot')
  event.removeAllTagsFrom('tconstruct:nickel_ingot')
  event.removeAllTagsFrom('cavesandcliffs:nickel_ingot')
  event.removeAllTagsFrom('tmechworks:nickel_ingot')

  event.removeAllTagsFrom('create:bronze_ingot')
  event.removeAllTagsFrom('forestry:ingot_bronze')
  event.removeAllTagsFrom('immersiveengineering:ingot_bronze')
  event.removeAllTagsFrom('mekanism:ingot_bronze')
  event.removeAllTagsFrom('occultism:bronze_ingot')
  event.removeAllTagsFrom('projectred-core:bronze_ingot')
  event.removeAllTagsFrom('tconstruct:bronze_ingot')
  event.removeAllTagsFrom('cavesandcliffs:bronze_ingot')
  event.removeAllTagsFrom('tmechworks:bronze_ingot')

  event.removeAllTagsFrom('create:electrum_ingot')
  event.removeAllTagsFrom('forestry:ingot_electrum')
  event.removeAllTagsFrom('immersiveengineering:ingot_electrum')
  event.removeAllTagsFrom('mekanism:ingot_electrum')
  event.removeAllTagsFrom('occultism:electrum_ingot')
  event.removeAllTagsFrom('projectred-core:electrum_ingot')
  event.removeAllTagsFrom('tconstruct:electrum_ingot')
  event.removeAllTagsFrom('cavesandcliffs:electrum_ingot')
  event.removeAllTagsFrom('tmechworks:electrum_ingot')

  event.removeAllTagsFrom('create:invar_ingot')
  event.removeAllTagsFrom('forestry:ingot_invar')
  event.removeAllTagsFrom('immersiveengineering:ingot_invar')
  event.removeAllTagsFrom('mekanism:ingot_invar')
  event.removeAllTagsFrom('occultism:invar_ingot')
  event.removeAllTagsFrom('projectred-core:invar_ingot')
  event.removeAllTagsFrom('tconstruct:invar_ingot')
  event.removeAllTagsFrom('cavesandcliffs:invar_ingot')
  event.removeAllTagsFrom('tmechworks:invar_ingot')

  event.removeAllTagsFrom('create:constantan_ingot')
  event.removeAllTagsFrom('forestry:ingot_constantan')
  event.removeAllTagsFrom('immersiveengineering:ingot_constantan')
  event.removeAllTagsFrom('mekanism:ingot_constantan')
  event.removeAllTagsFrom('occultism:constantan_ingot')
  event.removeAllTagsFrom('projectred-core:constantan_ingot')
  event.removeAllTagsFrom('tconstruct:constantan_ingot')
  event.removeAllTagsFrom('cavesandcliffs:constantan_ingot')
  event.removeAllTagsFrom('tmechworks:constantan_ingot')

  event.removeAllTagsFrom('create:signalum_ingot')
  event.removeAllTagsFrom('forestry:ingot_signalum')
  event.removeAllTagsFrom('immersiveengineering:ingot_signalum')
  event.removeAllTagsFrom('mekanism:ingot_signalum')
  event.removeAllTagsFrom('occultism:signalum_ingot')
  event.removeAllTagsFrom('projectred-core:signalum_ingot')
  event.removeAllTagsFrom('tconstruct:signalum_ingot')
  event.removeAllTagsFrom('cavesandcliffs:signalum_ingot')
  event.removeAllTagsFrom('tmechworks:signalum_ingot')

  event.removeAllTagsFrom('create:lumium_ingot')
  event.removeAllTagsFrom('forestry:ingot_lumium')
  event.removeAllTagsFrom('immersiveengineering:ingot_lumium')
  event.removeAllTagsFrom('mekanism:ingot_lumium')
  event.removeAllTagsFrom('occultism:lumium_ingot')
  event.removeAllTagsFrom('projectred-core:lumium_ingot')
  event.removeAllTagsFrom('tconstruct:lumium_ingot')
  event.removeAllTagsFrom('cavesandcliffs:lumium_ingot')
  event.removeAllTagsFrom('tmechworks:lumium_ingot')

  event.removeAllTagsFrom('create:enderium_ingot')
  event.removeAllTagsFrom('forestry:ingot_enderium')
  event.removeAllTagsFrom('immersiveengineering:ingot_enderium')
  event.removeAllTagsFrom('mekanism:ingot_enderium')
  event.removeAllTagsFrom('occultism:enderium_ingot')
  event.removeAllTagsFrom('projectred-core:enderium_ingot')
  event.removeAllTagsFrom('tconstruct:enderium_ingot')
  event.removeAllTagsFrom('cavesandcliffs:enderium_ingot')
  event.removeAllTagsFrom('tmechworks:enderium_ingot')

  event.removeAllTagsFrom('create:copper_plate')
  event.removeAllTagsFrom('forestry:plate_copper')
  event.removeAllTagsFrom('immersiveengineering:plate_copper')
  event.removeAllTagsFrom('mekanism:plate_copper')
  event.removeAllTagsFrom('occultism:copper_plate')
  event.removeAllTagsFrom('projectred-core:copper_plate')
  event.removeAllTagsFrom('tconstruct:copper_plate')
  event.removeAllTagsFrom('cavesandcliffs:copper_plate')
  event.removeAllTagsFrom('tmechworks:copper_plate')

  event.removeAllTagsFrom('create:tin_plate')
  event.removeAllTagsFrom('forestry:plate_tin')

  event.removeAllTagsFrom('immersiveengineering:plate_tin')
  event.removeAllTagsFrom('mekanism:plate_tin')
  event.removeAllTagsFrom('occultism:tin_plate')
  event.removeAllTagsFrom('projectred-core:tin_plate')
  event.removeAllTagsFrom('tconstruct:tin_plate')
  event.removeAllTagsFrom('cavesandcliffs:tin_plate')
  event.removeAllTagsFrom('tmechworks:tin_plate')

  event.removeAllTagsFrom('create:lead_plate')
  event.removeAllTagsFrom('forestry:plate_lead')
  event.removeAllTagsFrom('immersiveengineering:plate_lead')
  event.removeAllTagsFrom('mekanism:plate_lead')
  event.removeAllTagsFrom('occultism:lead_plate')
  event.removeAllTagsFrom('projectred-core:lead_plate')
  event.removeAllTagsFrom('tconstruct:lead_plate')
  event.removeAllTagsFrom('cavesandcliffs:lead_plate')
  event.removeAllTagsFrom('tmechworks:lead_plate')

  event.removeAllTagsFrom('create:silver_plate')
  event.removeAllTagsFrom('forestry:plate_silver')
  event.removeAllTagsFrom('immersiveengineering:plate_silver')
  event.removeAllTagsFrom('mekanism:plate_silver')
  event.removeAllTagsFrom('occultism:silver_plate')
  event.removeAllTagsFrom('projectred-core:silver_plate')
  event.removeAllTagsFrom('tconstruct:silver_plate')
  event.removeAllTagsFrom('cavesandcliffs:silver_plate')
  event.removeAllTagsFrom('tmechworks:silver_plate')

  event.removeAllTagsFrom('create:nickel_plate')
event.removeAllTagsFrom('forestry:plate_nickel')
event.removeAllTagsFrom('immersiveengineering:plate_nickel')
event.removeAllTagsFrom('mekanism:plate_nickel')
event.removeAllTagsFrom('occultism:nickel_plate')
event.removeAllTagsFrom('projectred-core:nickel_plate')
event.removeAllTagsFrom('tconstruct:nickel_plate')
event.removeAllTagsFrom('cavesandcliffs:nickel_plate')
event.removeAllTagsFrom('tmechworks:nickel_plate')

event.removeAllTagsFrom('create:bronze_plate')
event.removeAllTagsFrom('forestry:plate_bronze')
event.removeAllTagsFrom('immersiveengineering:plate_bronze')
event.removeAllTagsFrom('mekanism:plate_bronze')
event.removeAllTagsFrom('occultism:bronze_plate')
event.removeAllTagsFrom('projectred-core:bronze_plate')
event.removeAllTagsFrom('tconstruct:bronze_plate')
event.removeAllTagsFrom('cavesandcliffs:bronze_plate')
event.removeAllTagsFrom('tmechworks:bronze_plate')

event.removeAllTagsFrom('create:electrum_plate')
event.removeAllTagsFrom('forestry:plate_electrum')
event.removeAllTagsFrom('immersiveengineering:plate_electrum')
event.removeAllTagsFrom('mekanism:plate_electrum')
event.removeAllTagsFrom('occultism:electrum_plate')
event.removeAllTagsFrom('projectred-core:electrum_plate')
event.removeAllTagsFrom('tconstruct:electrum_plate')
event.removeAllTagsFrom('cavesandcliffs:electrum_plate')
event.removeAllTagsFrom('tmechworks:electrum_plate')

event.removeAllTagsFrom('create:invar_plate')
event.removeAllTagsFrom('forestry:plate_invar')
event.removeAllTagsFrom('immersiveengineering:plate_invar')
event.removeAllTagsFrom('mekanism:plate_invar')
event.removeAllTagsFrom('occultism:invar_plate')
event.removeAllTagsFrom('projectred-core:invar_plate')
event.removeAllTagsFrom('tconstruct:invar_plate')
event.removeAllTagsFrom('cavesandcliffs:invar_plate')
event.removeAllTagsFrom('tmechworks:invar_plate')

event.removeAllTagsFrom('create:constantan_plate')
event.removeAllTagsFrom('forestry:plate_constantan')
event.removeAllTagsFrom('immersiveengineering:plate_constantan')
event.removeAllTagsFrom('mekanism:plate_constantan')
event.removeAllTagsFrom('occultism:constantan_plate')
event.removeAllTagsFrom('projectred-core:constantan_plate')
event.removeAllTagsFrom('tconstruct:constantan_plate')
event.removeAllTagsFrom('cavesandcliffs:constantan_plate')
event.removeAllTagsFrom('tmechworks:constantan_plate')

event.removeAllTagsFrom('create:signalum_plate')
event.removeAllTagsFrom('forestry:plate_signalum')
event.removeAllTagsFrom('immersiveengineering:plate_signalum')
event.removeAllTagsFrom('mekanism:plate_signalum')
event.removeAllTagsFrom('occultism:signalum_plate')
event.removeAllTagsFrom('projectred-core:signalum_plate')
event.removeAllTagsFrom('tconstruct:signalum_plate')
event.removeAllTagsFrom('cavesandcliffs:signalum_plate')
event.removeAllTagsFrom('tmechworks:signalum_plate')

event.removeAllTagsFrom('create:lumium_plate')
event.removeAllTagsFrom('forestry:plate_lumium')
event.removeAllTagsFrom('immersiveengineering:plate_lumium')
event.removeAllTagsFrom('mekanism:plate_lumium')
event.removeAllTagsFrom('occultism:lumium_plate')
event.removeAllTagsFrom('projectred-core:lumium_plate')
event.removeAllTagsFrom('tconstruct:lumium_plate')
event.removeAllTagsFrom('cavesandcliffs:lumium_plate')
event.removeAllTagsFrom('tmechworks:lumium_plate')

event.removeAllTagsFrom('create:enderium_plate')
event.removeAllTagsFrom('forestry:plate_enderium')
event.removeAllTagsFrom('immersiveengineering:plate_enderium')
event.removeAllTagsFrom('mekanism:plate_enderium')
event.removeAllTagsFrom('occultism:enderium_plate')
event.removeAllTagsFrom('projectred-core:enderium_plate')
event.removeAllTagsFrom('tconstruct:enderium_plate')
event.removeAllTagsFrom('cavesandcliffs:enderium_plate')
event.removeAllTagsFrom('tmechworks:enderium_plate')

event.removeAllTagsFrom('create:copper_dust')
event.removeAllTagsFrom('forestry:dust_copper')
event.removeAllTagsFrom('immersiveengineering:dust_copper')
event.removeAllTagsFrom('mekanism:dust_copper')
event.removeAllTagsFrom('occultism:copper_dust')
event.removeAllTagsFrom('projectred-core:copper_dust')
event.removeAllTagsFrom('tconstruct:copper_dust')
event.removeAllTagsFrom('cavesandcliffs:copper_dust')
event.removeAllTagsFrom('tmechworks:copper_dust')

event.removeAllTagsFrom('create:tin_dust')
event.removeAllTagsFrom('forestry:dust_tin')
event.removeAllTagsFrom('immersiveengineering:dust_tin')
event.removeAllTagsFrom('mekanism:dust_tin')
event.removeAllTagsFrom('occultism:tin_dust')
event.removeAllTagsFrom('projectred-core:tin_dust')
event.removeAllTagsFrom('tconstruct:tin_dust')
event.removeAllTagsFrom('cavesandcliffs:tin_dust')
event.removeAllTagsFrom('tmechworks:tin_dust')

event.removeAllTagsFrom('create:lead_dust')
event.removeAllTagsFrom('forestry:dust_lead')
event.removeAllTagsFrom('immersiveengineering:dust_lead')
event.removeAllTagsFrom('mekanism:dust_lead')
event.removeAllTagsFrom('occultism:lead_dust')
event.removeAllTagsFrom('projectred-core:lead_dust')
event.removeAllTagsFrom('tconstruct:lead_dust')
event.removeAllTagsFrom('cavesandcliffs:lead_dust')
event.removeAllTagsFrom('tmechworks:lead_dust')

event.removeAllTagsFrom('create:silver_dust')
event.removeAllTagsFrom('forestry:dust_silver')
event.removeAllTagsFrom('immersiveengineering:dust_silver')
event.removeAllTagsFrom('mekanism:dust_silver')
event.removeAllTagsFrom('occultism:silver_dust')
event.removeAllTagsFrom('projectred-core:silver_dust')
event.removeAllTagsFrom('tconstruct:silver_dust')
event.removeAllTagsFrom('cavesandcliffs:silver_dust')
event.removeAllTagsFrom('tmechworks:silver_dust')

event.removeAllTagsFrom('create:nickel_dust')
event.removeAllTagsFrom('forestry:dust_nickel')
event.removeAllTagsFrom('immersiveengineering:dust_nickel')
event.removeAllTagsFrom('mekanism:dust_nickel')
event.removeAllTagsFrom('occultism:nickel_dust')
event.removeAllTagsFrom('projectred-core:nickel_dust')
event.removeAllTagsFrom('tconstruct:nickel_dust')
event.removeAllTagsFrom('cavesandcliffs:nickel_dust')
event.removeAllTagsFrom('tmechworks:nickel_dust')

event.removeAllTagsFrom('create:bronze_dust')
event.removeAllTagsFrom('forestry:dust_bronze')
event.removeAllTagsFrom('immersiveengineering:dust_bronze')
event.removeAllTagsFrom('mekanism:dust_bronze')
event.removeAllTagsFrom('occultism:bronze_dust')
event.removeAllTagsFrom('projectred-core:bronze_dust')
event.removeAllTagsFrom('tconstruct:bronze_dust')
event.removeAllTagsFrom('cavesandcliffs:bronze_dust')
event.removeAllTagsFrom('tmechworks:bronze_dust')

event.removeAllTagsFrom('create:electrum_dust')
event.removeAllTagsFrom('forestry:dust_electrum')
event.removeAllTagsFrom('immersiveengineering:dust_electrum')
event.removeAllTagsFrom('mekanism:dust_electrum')
event.removeAllTagsFrom('occultism:electrum_dust')
event.removeAllTagsFrom('projectred-core:electrum_dust')
event.removeAllTagsFrom('tconstruct:electrum_dust')
event.removeAllTagsFrom('cavesandcliffs:electrum_dust')
event.removeAllTagsFrom('tmechworks:electrum_dust')

event.removeAllTagsFrom('create:invar_dust')
event.removeAllTagsFrom('forestry:dust_invar')
event.removeAllTagsFrom('immersiveengineering:dust_invar')
event.removeAllTagsFrom('mekanism:dust_invar')
event.removeAllTagsFrom('occultism:invar_dust')
event.removeAllTagsFrom('projectred-core:invar_dust')
event.removeAllTagsFrom('tconstruct:invar_dust')
event.removeAllTagsFrom('cavesandcliffs:invar_dust')
event.removeAllTagsFrom('tmechworks:invar_dust')

event.removeAllTagsFrom('create:constantan_dust')
event.removeAllTagsFrom('forestry:dust_constantan')
event.removeAllTagsFrom('immersiveengineering:dust_constantan')
event.removeAllTagsFrom('mekanism:dust_constantan')
event.removeAllTagsFrom('occultism:constantan_dust')
event.removeAllTagsFrom('projectred-core:constantan_dust')
event.removeAllTagsFrom('tconstruct:constantan_dust')
event.removeAllTagsFrom('cavesandcliffs:constantan_dust')
event.removeAllTagsFrom('tmechworks:constantan_dust')

event.removeAllTagsFrom('create:signalum_dust')
event.removeAllTagsFrom('forestry:dust_signalum')
event.removeAllTagsFrom('immersiveengineering:dust_signalum')
event.removeAllTagsFrom('mekanism:dust_signalum')
event.removeAllTagsFrom('occultism:signalum_dust')
event.removeAllTagsFrom('projectred-core:signalum_dust')
event.removeAllTagsFrom('tconstruct:signalum_dust')
event.removeAllTagsFrom('cavesandcliffs:signalum_dust')
event.removeAllTagsFrom('tmechworks:signalum_dust')

event.removeAllTagsFrom('create:lumium_dust')
event.removeAllTagsFrom('forestry:dust_lumium')
event.removeAllTagsFrom('immersiveengineering:dust_lumium')
event.removeAllTagsFrom('mekanism:dust_lumium')
event.removeAllTagsFrom('occultism:lumium_dust')
event.removeAllTagsFrom('projectred-core:lumium_dust')
event.removeAllTagsFrom('tconstruct:lumium_dust')
event.removeAllTagsFrom('cavesandcliffs:lumium_dust')
event.removeAllTagsFrom('tmechworks:lumium_dust')

event.removeAllTagsFrom('create:enderium_dust')
event.removeAllTagsFrom('forestry:dust_enderium')
event.removeAllTagsFrom('immersiveengineering:dust_enderium')
event.removeAllTagsFrom('mekanism:dust_enderium')
event.removeAllTagsFrom('occultism:enderium_dust')
event.removeAllTagsFrom('projectred-core:enderium_dust')
event.removeAllTagsFrom('tconstruct:enderium_dust')
event.removeAllTagsFrom('cavesandcliffs:enderium_dust')
event.removeAllTagsFrom('tmechworks:enderium_dust')


event.removeAllTagsFrom('create:copper_gear')
event.removeAllTagsFrom('forestry:gear_copper')
event.removeAllTagsFrom('immersiveengineering:gear_copper')
event.removeAllTagsFrom('mekanism:gear_copper')
event.removeAllTagsFrom('occultism:copper_gear')
event.removeAllTagsFrom('projectred-core:copper_gear')
event.removeAllTagsFrom('tconstruct:copper_gear')
event.removeAllTagsFrom('cavesandcliffs:copper_gear')
event.removeAllTagsFrom('tmechworks:copper_gear')

event.removeAllTagsFrom('create:tin_gear')
event.removeAllTagsFrom('forestry:gear_tin')
event.removeAllTagsFrom('immersiveengineering:gear_tin')
event.removeAllTagsFrom('mekanism:gear_tin')
event.removeAllTagsFrom('occultism:tin_gear')
event.removeAllTagsFrom('projectred-core:tin_gear')
event.removeAllTagsFrom('tconstruct:tin_gear')
event.removeAllTagsFrom('cavesandcliffs:tin_gear')

event.removeAllTagsFrom('create:lead_gear')
event.removeAllTagsFrom('forestry:gear_lead')
event.removeAllTagsFrom('immersiveengineering:gear_lead')
event.removeAllTagsFrom('mekanism:gear_lead')
event.removeAllTagsFrom('occultism:lead_gear')
event.removeAllTagsFrom('projectred-core:lead_gear')
event.removeAllTagsFrom('tconstruct:lead_gear')
event.removeAllTagsFrom('cavesandcliffs:lead_gear')
event.removeAllTagsFrom('tmechworks:lead_gear')

event.removeAllTagsFrom('create:silver_gear')
event.removeAllTagsFrom('forestry:gear_silver')
event.removeAllTagsFrom('immersiveengineering:gear_silver')
event.removeAllTagsFrom('mekanism:gear_silver')
event.removeAllTagsFrom('occultism:silver_gear')
event.removeAllTagsFrom('projectred-core:silver_gear')
event.removeAllTagsFrom('tconstruct:silver_gear')
event.removeAllTagsFrom('cavesandcliffs:silver_gear')
event.removeAllTagsFrom('tmechworks:silver_gear')

event.removeAllTagsFrom('create:nickel_gear')
event.removeAllTagsFrom('forestry:gear_nickel')
event.removeAllTagsFrom('immersiveengineering:gear_nickel')
event.removeAllTagsFrom('mekanism:gear_nickel')
event.removeAllTagsFrom('occultism:nickel_gear')
event.removeAllTagsFrom('projectred-core:nickel_gear')
event.removeAllTagsFrom('tconstruct:nickel_gear')
event.removeAllTagsFrom('cavesandcliffs:nickel_gear')
event.removeAllTagsFrom('tmechworks:nickel_gear')

event.removeAllTagsFrom('create:bronze_gear')
event.removeAllTagsFrom('forestry:gear_bronze')
event.removeAllTagsFrom('immersiveengineering:gear_bronze')
event.removeAllTagsFrom('mekanism:gear_bronze')
event.removeAllTagsFrom('occultism:bronze_gear')
event.removeAllTagsFrom('projectred-core:bronze_gear')
event.removeAllTagsFrom('tconstruct:bronze_gear')
event.removeAllTagsFrom('cavesandcliffs:bronze_gear')
event.removeAllTagsFrom('tmechworks:bronze_gear')

event.removeAllTagsFrom('create:electrum_gear')
event.removeAllTagsFrom('forestry:gear_electrum')
event.removeAllTagsFrom('immersiveengineering:gear_electrum')
event.removeAllTagsFrom('mekanism:gear_electrum')
event.removeAllTagsFrom('occultism:electrum_gear')
event.removeAllTagsFrom('projectred-core:electrum_gear')
event.removeAllTagsFrom('tconstruct:electrum_gear')
event.removeAllTagsFrom('cavesandcliffs:electrum_gear')
event.removeAllTagsFrom('tmechworks:electrum_gear')

event.removeAllTagsFrom('create:invar_gear')
event.removeAllTagsFrom('forestry:gear_invar')
event.removeAllTagsFrom('immersiveengineering:gear_invar')
event.removeAllTagsFrom('mekanism:gear_invar')
event.removeAllTagsFrom('occultism:invar_gear')
event.removeAllTagsFrom('projectred-core:invar_gear')
event.removeAllTagsFrom('tconstruct:invar_gear')
event.removeAllTagsFrom('cavesandcliffs:invar_gear')
event.removeAllTagsFrom('tmechworks:invar_gear')

event.removeAllTagsFrom('create:constantan_gear')
event.removeAllTagsFrom('forestry:gear_constantan')
event.removeAllTagsFrom('immersiveengineering:gear_constantan')
event.removeAllTagsFrom('mekanism:gear_constantan')
event.removeAllTagsFrom('occultism:constantan_gear')
event.removeAllTagsFrom('projectred-core:constantan_gear')
event.removeAllTagsFrom('tconstruct:constantan_gear')
event.removeAllTagsFrom('cavesandcliffs:constantan_gear')
event.removeAllTagsFrom('tmechworks:constantan_gear')

event.removeAllTagsFrom('create:signalum_gear')
event.removeAllTagsFrom('forestry:gear_signalum')
event.removeAllTagsFrom('immersiveengineering:gear_signalum')
event.removeAllTagsFrom('mekanism:gear_signalum')
event.removeAllTagsFrom('occultism:signalum_gear')
event.removeAllTagsFrom('projectred-core:signalum_gear')
event.removeAllTagsFrom('tconstruct:signalum_gear')
event.removeAllTagsFrom('cavesandcliffs:signalum_gear')
event.removeAllTagsFrom('tmechworks:signalum_gear')

event.removeAllTagsFrom('create:lumium_gear')
event.removeAllTagsFrom('forestry:gear_lumium')
event.removeAllTagsFrom('immersiveengineering:gear_lumium')
event.removeAllTagsFrom('mekanism:gear_lumium')
event.removeAllTagsFrom('occultism:lumium_gear')
event.removeAllTagsFrom('projectred-core:lumium_gear')
event.removeAllTagsFrom('tconstruct:lumium_gear')
event.removeAllTagsFrom('cavesandcliffs:lumium_gear')
event.removeAllTagsFrom('tmechworks:lumium_gear')

event.removeAllTagsFrom('create:enderium_gear')
event.removeAllTagsFrom('forestry:gear_enderium')
event.removeAllTagsFrom('immersiveengineering:gear_enderium')
event.removeAllTagsFrom('mekanism:gear_enderium')
event.removeAllTagsFrom('occultism:enderium_gear')
event.removeAllTagsFrom('projectred-core:enderium_gear')
event.removeAllTagsFrom('tconstruct:enderium_gear')
event.removeAllTagsFrom('cavesandcliffs:enderium_gear')
event.removeAllTagsFrom('tmechworks:enderium_gear')

event.removeAllTagsFrom('mekanism:ingot_uranium')
event.removeAllTagsFrom('tmechworks:aluminum_ingot')
event.removeAllTagsFrom('mekanism:dust_steel')
event.removeAllTagsFrom('mekanism:ingot_steel')
event.removeAllTagsFrom('mekanism:nugget_steel')
event.removeAllTagsFrom('mekanism:block_steel')
event.removeAllTagsFrom('mekanism:dust_uranium')
event.removeAllTagsFrom('mekanism:ingot_uranium')
event.removeAllTagsFrom('mekanism:nugget_uranium')
event.removeAllTagsFrom('mekanism:block_uranium')

event.removeAllTagsFrom('create:copper_nugget') 
event.removeAllTagsFrom('immersiveengineering:nugget_copper')
event.removeAllTagsFrom('mekanism:nugget_copper') 
event.removeAllTagsFrom('occultism:copper_nugget') 
event.removeAllTagsFrom('tconstruct:copper_nugget')
event.removeAllTagsFrom('tmechworks:copper_nugget')
event.removeAllTagsFrom('boss_tools:copper_nugget')
event.removeAllTagsFrom('mekanism:nugget_copper')

event.removeAllTagsFrom('create:tin_nugget') 
event.removeAllTagsFrom('immersiveengineering:nugget_tin')
event.removeAllTagsFrom('mekanism:nugget_tin') 
event.removeAllTagsFrom('occultism:tin_nugget') 
event.removeAllTagsFrom('tconstruct:tin_nugget')
event.removeAllTagsFrom('tmechworks:tin_nugget')
event.removeAllTagsFrom('boss_tools:tin_nugget')
event.removeAllTagsFrom('mekanism:nugget_tin')

event.removeAllTagsFrom('create:lead_nugget') 
event.removeAllTagsFrom('immersiveengineering:nugget_lead')
event.removeAllTagsFrom('mekanism:nugget_lead') 
event.removeAllTagsFrom('occultism:lead_nugget') 
event.removeAllTagsFrom('tconstruct:lead_nugget')
event.removeAllTagsFrom('tmechworks:lead_nugget')
event.removeAllTagsFrom('boss_tools:lead_nugget')
event.removeAllTagsFrom('mekanism:nugget_lead')

event.removeAllTagsFrom('create:silver_nugget') 
event.removeAllTagsFrom('immersiveengineering:nugget_silver')
event.removeAllTagsFrom('mekanism:nugget_silver') 
event.removeAllTagsFrom('occultism:silver_nugget') 
event.removeAllTagsFrom('tconstruct:silver_nugget')
event.removeAllTagsFrom('tmechworks:silver_nugget')
event.removeAllTagsFrom('boss_tools:silver_nugget')
event.removeAllTagsFrom('mekanism:nugget_silver')

event.removeAllTagsFrom('create:nickel_nugget') 
event.removeAllTagsFrom('immersiveengineering:nugget_nickel')
event.removeAllTagsFrom('mekanism:nugget_nickel') 
event.removeAllTagsFrom('occultism:nickel_nugget') 
event.removeAllTagsFrom('tconstruct:nickel_nugget')
event.removeAllTagsFrom('tmechworks:nickel_nugget')
event.removeAllTagsFrom('boss_tools:nickel_nugget')
event.removeAllTagsFrom('mekanism:nugget_nickel')

event.removeAllTagsFrom('create:bronze_nugget') 
event.removeAllTagsFrom('immersiveengineering:nugget_bronze')
event.removeAllTagsFrom('mekanism:nugget_bronze') 
event.removeAllTagsFrom('occultism:bronze_nugget') 
event.removeAllTagsFrom('tconstruct:bronze_nugget')
event.removeAllTagsFrom('tmechworks:bronze_nugget')
event.removeAllTagsFrom('boss_tools:bronze_nugget')
event.removeAllTagsFrom('mekanism:nugget_bronze')

event.removeAllTagsFrom('create:electrum_nugget') 
event.removeAllTagsFrom('immersiveengineering:nugget_electrum')
event.removeAllTagsFrom('mekanism:nugget_electrum') 
event.removeAllTagsFrom('occultism:electrum_nugget') 
event.removeAllTagsFrom('tconstruct:electrum_nugget')
event.removeAllTagsFrom('tmechworks:electrum_nugget')
event.removeAllTagsFrom('boss_tools:electrum_nugget')
event.removeAllTagsFrom('mekanism:nugget_electrum')

event.removeAllTagsFrom('create:invar_nugget') 
event.removeAllTagsFrom('immersiveengineering:nugget_invar')
event.removeAllTagsFrom('mekanism:nugget_invar') 
event.removeAllTagsFrom('occultism:invar_nugget') 
event.removeAllTagsFrom('tconstruct:invar_nugget')
event.removeAllTagsFrom('tmechworks:invar_nugget')
event.removeAllTagsFrom('boss_tools:invar_nugget')
event.removeAllTagsFrom('mekanism:nugget_invar')

event.removeAllTagsFrom('create:constantan_nugget') 
event.removeAllTagsFrom('immersiveengineering:nugget_constantan')
event.removeAllTagsFrom('mekanism:nugget_constantan') 
event.removeAllTagsFrom('occultism:constantan_nugget') 
event.removeAllTagsFrom('tconstruct:constantan_nugget')
event.removeAllTagsFrom('tmechworks:constantan_nugget')
event.removeAllTagsFrom('boss_tools:constantan_nugget')
event.removeAllTagsFrom('mekanism:nugget_constantan')

event.removeAllTagsFrom('create:lumium_nugget') 
event.removeAllTagsFrom('immersiveengineering:nugget_lumium')
event.removeAllTagsFrom('mekanism:nugget_lumium') 
event.removeAllTagsFrom('occultism:lumium_nugget') 
event.removeAllTagsFrom('tconstruct:lumium_nugget')
event.removeAllTagsFrom('tmechworks:lumium_nugget')
event.removeAllTagsFrom('boss_tools:lumium_nugget')
event.removeAllTagsFrom('mekanism:nugget_lumium')

event.removeAllTagsFrom('create:signalum_nugget') 
event.removeAllTagsFrom('immersiveengineering:nugget_signalum')
event.removeAllTagsFrom('mekanism:nugget_signalum') 
event.removeAllTagsFrom('occultism:signalum_nugget') 
event.removeAllTagsFrom('tconstruct:signalum_nugget')
event.removeAllTagsFrom('tmechworks:signalum_nugget')
event.removeAllTagsFrom('boss_tools:signalum_nugget')
event.removeAllTagsFrom('mekanism:nugget_signalum')

event.removeAllTagsFrom('create:enderium_nugget') 
event.removeAllTagsFrom('immersiveengineering:nugget_enderium')
event.removeAllTagsFrom('mekanism:nugget_enderium') 
event.removeAllTagsFrom('occultism:enderium_nugget') 
event.removeAllTagsFrom('tconstruct:enderium_nugget')
event.removeAllTagsFrom('tmechworks:enderium_nugget')
event.removeAllTagsFrom('boss_tools:enderium_nugget')
event.removeAllTagsFrom('mekanism:nugget_enderium')

event.removeAllTagsFrom('boss_tools:steel_nugget')
event.removeAllTagsFrom('mekanism:nugget_steel')
event.removeAllTagsFrom('boss_tools:uranium_nugget')
event.removeAllTagsFrom('mekanism:uranium_steel')

event.removeAllTagsFrom('create:copper_block') 
event.removeAllTagsFrom('forestry:resource_storage_copper') 
event.removeAllTagsFrom('immersiveengineering:storage_copper') 
event.removeAllTagsFrom('occultism:copper_block') 
event.removeAllTagsFrom('tconstruct:copper_block') 
event.removeAllTagsFrom('cavesandcliffs:copper_block') 
event.removeAllTagsFrom('tmechworks:copper_block')

event.removeAllTagsFrom('create:tin_block') 
event.removeAllTagsFrom('forestry:resource_storage_tin') 
event.removeAllTagsFrom('immersiveengineering:storage_tin') 
event.removeAllTagsFrom('occultism:tin_block') 
event.removeAllTagsFrom('tconstruct:tin_block') 
event.removeAllTagsFrom('cavesandcliffs:tin_block') 
event.removeAllTagsFrom('tmechworks:tin_block')

event.removeAllTagsFrom('create:lead_block') 
event.removeAllTagsFrom('forestry:resource_storage_lead') 
event.removeAllTagsFrom('immersiveengineering:storage_lead') 
event.removeAllTagsFrom('occultism:lead_block') 
event.removeAllTagsFrom('tconstruct:lead_block') 
event.removeAllTagsFrom('cavesandcliffs:lead_block') 
event.removeAllTagsFrom('tmechworks:lead_block')

event.removeAllTagsFrom('create:silver_block') 
event.removeAllTagsFrom('forestry:resource_storage_silver') 
event.removeAllTagsFrom('immersiveengineering:storage_silver') 
event.removeAllTagsFrom('occultism:silver_block') 
event.removeAllTagsFrom('tconstruct:silver_block') 
event.removeAllTagsFrom('cavesandcliffs:silver_block') 
event.removeAllTagsFrom('tmechworks:silver_block')

event.removeAllTagsFrom('create:electrum_block') 
event.removeAllTagsFrom('forestry:resource_storage_electrum') 
event.removeAllTagsFrom('immersiveengineering:storage_electrum') 
event.removeAllTagsFrom('occultism:electrum_block') 
event.removeAllTagsFrom('tconstruct:electrum_block') 
event.removeAllTagsFrom('cavesandcliffs:electrum_block') 
event.removeAllTagsFrom('tmechworks:electrum_block')

event.removeAllTagsFrom('create:invar_block') 
event.removeAllTagsFrom('forestry:resource_storage_invar') 
event.removeAllTagsFrom('immersiveengineering:storage_invar') 
event.removeAllTagsFrom('occultism:invar_block') 
event.removeAllTagsFrom('tconstruct:invar_block') 
event.removeAllTagsFrom('cavesandcliffs:invar_block') 
event.removeAllTagsFrom('tmechworks:invar_block')

event.removeAllTagsFrom('create:nickel_block') 
event.removeAllTagsFrom('forestry:resource_storage_nickel') 
event.removeAllTagsFrom('immersiveengineering:storage_nickel') 
event.removeAllTagsFrom('occultism:nickel_block') 
event.removeAllTagsFrom('tconstruct:nickel_block') 
event.removeAllTagsFrom('cavesandcliffs:nickel_block') 
event.removeAllTagsFrom('tmechworks:nickel_block')

event.removeAllTagsFrom('create:constantan_block') 
event.removeAllTagsFrom('forestry:resource_storage_constantan') 
event.removeAllTagsFrom('immersiveengineering:storage_constantan') 
event.removeAllTagsFrom('occultism:constantan_block') 
event.removeAllTagsFrom('tconstruct:constantan_block') 
event.removeAllTagsFrom('cavesandcliffs:constantan_block') 
event.removeAllTagsFrom('tmechworks:constantan_block')

event.removeAllTagsFrom('create:signalum_block') 
event.removeAllTagsFrom('forestry:resource_storage_signalum') 
event.removeAllTagsFrom('immersiveengineering:storage_signalum') 
event.removeAllTagsFrom('occultism:signalum_block') 
event.removeAllTagsFrom('tconstruct:signalum_block') 
event.removeAllTagsFrom('cavesandcliffs:signalum_block') 
event.removeAllTagsFrom('tmechworks:signalum_block')

event.removeAllTagsFrom('create:lumium_block') 
event.removeAllTagsFrom('forestry:resource_storage_lumium') 
event.removeAllTagsFrom('immersiveengineering:storage_lumium') 
event.removeAllTagsFrom('occultism:lumium_block') 
event.removeAllTagsFrom('tconstruct:lumium_block') 
event.removeAllTagsFrom('cavesandcliffs:lumium_block') 
event.removeAllTagsFrom('tmechworks:lumium_block')

event.removeAllTagsFrom('create:enderium_block') 
event.removeAllTagsFrom('forestry:resource_storage_enderium') 
event.removeAllTagsFrom('immersiveengineering:storage_enderium') 
event.removeAllTagsFrom('occultism:enderium_block') 
event.removeAllTagsFrom('tconstruct:enderium_block') 
event.removeAllTagsFrom('cavesandcliffs:enderium_block') 
event.removeAllTagsFrom('tmechworks:enderium_block')

event.removeAllTagsFrom('boss_tools:steel_block') 
event.removeAllTagsFrom('mekanism:block_steel')
event.removeAllTagsFrom('boss_tools:uranium_block') 
event.removeAllTagsFrom('mekanism:uranium_steel')

event.removeAllTagsFrom('mekanism:block_tin')
event.removeAllTagsFrom('mekanism:block_lead')
event.removeAllTagsFrom('mekanism:block_bronze')
event.removeAllTagsFrom('mekanism:block_copper')

event.removeAllTagsFrom('occultism:iron_dust')
event.removeAllTagsFrom('mekanism:dust_iron')
event.removeAllTagsFrom('immersiveengineering:dust_iron')
event.removeAllTagsFrom('occultism:gold_dust')
event.removeAllTagsFrom('mekanism:dust_gold')
event.removeAllTagsFrom('immersiveengineering:dust_gold')

event.removeAllTagsFrom('immersiveengineering:plate_iron')
event.removeAllTagsFrom('boss_tools:iron_plate')
event.removeAllTagsFrom('create:iron_sheet')
event.removeAllTagsFrom('boss_tools:gold_plate')
event.removeAllTagsFrom('create:golden_sheet')
event.removeAllTagsFrom('immersiveengineering:plate_tin')

event.removeAllTagsFrom('boss_tools:tin_plate')
event.removeAllTagsFrom('create:tin_sheet')
event.removeAllTagsFrom('immersiveengineering:plate_silver')

event.removeAllTagsFrom('boss_tools:silver_plate')
event.removeAllTagsFrom('create:silver_sheet')
event.removeAllTagsFrom('immersiveengineering:plate_lead')

event.removeAllTagsFrom('boss_tools:lead_plate')
event.removeAllTagsFrom('create:lead_sheet')
event.removeAllTagsFrom('immersiveengineering:plate_silver')

event.removeAllTagsFrom('boss_tools:silver_plate')
event.removeAllTagsFrom('create:silver_sheet')
event.removeAllTagsFrom('immersiveengineering:plate_nickel')

event.removeAllTagsFrom('boss_tools:nickel_plate')
event.removeAllTagsFrom('create:nickel_sheet')
event.removeAllTagsFrom('immersiveengineering:plate_bronze')

event.removeAllTagsFrom('boss_tools:bronze_plate')
event.removeAllTagsFrom('create:bronze_sheet')
event.removeAllTagsFrom('immersiveengineering:plate_electrum')

event.removeAllTagsFrom('boss_tools:electrum_plate')
event.removeAllTagsFrom('create:electrum_sheet')
event.removeAllTagsFrom('immersiveengineering:plate_invar')

event.removeAllTagsFrom('boss_tools:invar_plate')
event.removeAllTagsFrom('create:invar_sheet')
event.removeAllTagsFrom('immersiveengineering:plate_constantan')

event.removeAllTagsFrom('boss_tools:constantan_plate')
event.removeAllTagsFrom('create:constantan_sheet')
event.removeAllTagsFrom('immersiveengineering:plate_signalum')

event.removeAllTagsFrom('boss_tools:signalum_plate')
event.removeAllTagsFrom('create:signalum_sheet')
event.removeAllTagsFrom('immersiveengineering:plate_lumium')

event.removeAllTagsFrom('boss_tools:lumium_plate')
event.removeAllTagsFrom('create:lumium_sheet')
event.removeAllTagsFrom('immersiveengineering:plate_enderium')

event.removeAllTagsFrom('boss_tools:enderium_plate')
event.removeAllTagsFrom('create:enderium_sheet')
event.removeAllTagsFrom('create:brass_sheet')
event.removeAllTagsFrom('createaddition:zinc_sheet')

event.removeAllTagsFrom('miniutilities:ender_dust')

event.add('forge:dusts/ender', 'thermal:ender_pearl_dust')
event.add('forge:dragonheart', 'draconicevolution:dragon_heart')
event.add('forge:hammermaterial', 'thermal:copper_ingot') 
event.add('forge:hammermaterial', 'thermal:tin_ingot') 
event.add('forge:hammermaterial', 'thermal:lead_ingot') 
event.add('forge:hammermaterial', 'thermal:silver_ingot') 
event.add('forge:hammermaterial', 'thermal:nickel_ingot') 
event.add('forge:hammermaterial', 'thermal:bronze_ingot') 
event.add('forge:hammermaterial', 'thermal:electrum_ingot') 
event.add('forge:hammermaterial', 'thermal:invar_ingot') 
event.add('forge:hammermaterial', 'thermal:constantan_ingot') 
event.add('forge:hammermaterial', '#forge:ingots/osmium') 
event.add('forge:hammermaterial', '#forge:ingots/uranium')
event.add('forge:hammermaterial', '#forge:ingots/iron') 
event.add('forge:hammermaterial', '#forge:ingots/gold')
event.removeAllTagsFrom('immersiveengineering:dust_sulfur')
event.removeAllTagsFrom('immersiveengineering:dust_wood')
event.removeAllTagsFrom('forbidden_arcanus:arcane_gold_ingot')
event.removeAllTagsFrom('eidolon:lead_ingot')
event.removeAllTagsFrom('tmechworks:aluminum_block')
event.removeAllTagsFrom('create:copper_sheet')
































































})
