onEvent('recipes', event => {

    event.remove({output: 'mekanism:ingot_uranium'})
    event.remove({output: 'tmechworks:aluminum_ingot'})


    event.remove({output: 'create:copper_ingot'})
    event.remove({output: 'forestry:ingot_copper'})
    event.remove({output: 'iceandfire:copper_ingot'})
    event.remove({output: 'immersiveengineering:ingot_copper'})
    event.remove({output: 'mekanism:ingot_copper'})
    event.remove({output: 'occultism:copper_ingot'})
    event.remove({output: 'projectred-core:copper_ingot'})
    event.remove({output: 'tconstruct:copper_ingot'})
    event.remove({output: 'cavesandcliffs:copper_ingot'})
    event.remove({output: 'tmechworks:copper_ingot'})
    event.remove({output: 'tmechworks:aluminum_block'})

    event.remove({output: 'create:tin_ingot'})
    event.remove({output: 'forestry:ingot_tin'})
    event.remove({output: 'iceandfire:tin_ingot'})
    event.remove({output: 'immersiveengineering:ingot_tin'})
    event.remove({output: 'mekanism:ingot_tin'})
    event.remove({output: 'occultism:tin_ingot'})
    event.remove({output: 'projectred-core:tin_ingot'})
    event.remove({output: 'tconstruct:tin_ingot'})
    event.remove({output: 'cavesandcliffs:tin_ingot'})
    event.remove({output: 'tmechworks:tin_ingot'})

    event.remove({output: 'create:lead_ingot'})
    event.remove({output: 'forestry:ingot_lead'})
    event.remove({output: 'iceandfire:lead_ingot'})
    event.remove({output: 'immersiveengineering:ingot_lead'})
    event.remove({output: 'mekanism:ingot_lead'})
    event.remove({output: 'occultism:lead_ingot'})
    event.remove({output: 'projectred-core:lead_ingot'})
    event.remove({output: 'tconstruct:lead_ingot'})
    event.remove({output: 'cavesandcliffs:lead_ingot'})
    event.remove({output: 'tmechworks:lead_ingot'})

    event.remove({output: 'create:silver_ingot'})
    event.remove({output: 'forestry:ingot_silver'})
    event.remove({output: 'iceandfire:silver_ingot'})
    event.remove({output: 'immersiveengineering:ingot_silver'})
    event.remove({output: 'mekanism:ingot_silver'})
    event.remove({output: 'occultism:silver_ingot'})
    event.remove({output: 'projectred-core:silver_ingot'})
    event.remove({output: 'tconstruct:silver_ingot'})
    event.remove({output: 'cavesandcliffs:silver_ingot'})
    event.remove({output: 'tmechworks:silver_ingot'})

    event.remove({output: 'create:nickel_ingot'})
  event.remove({output: 'forestry:ingot_nickel'})
  event.remove({output: 'iceandfire:nickel_ingot'})
  event.remove({output: 'immersiveengineering:ingot_nickel'})
  event.remove({output: 'mekanism:ingot_nickel'})
  event.remove({output: 'occultism:nickel_ingot'})
  event.remove({output: 'projectred-core:nickel_ingot'})
  event.remove({output: 'tconstruct:nickel_ingot'})
  event.remove({output: 'cavesandcliffs:nickel_ingot'})
  event.remove({output: 'tmechworks:nickel_ingot'})

  event.remove({output: 'create:bronze_ingot'})
  event.remove({output: 'forestry:ingot_bronze'})
  event.remove({output: 'iceandfire:bronze_ingot'})
  event.remove({output: 'immersiveengineering:ingot_bronze'})
  event.remove({output: 'mekanism:ingot_bronze'})
  event.remove({output: 'occultism:bronze_ingot'})
  event.remove({output: 'projectred-core:bronze_ingot'})
  event.remove({output: 'tconstruct:bronze_ingot'})
  event.remove({output: 'cavesandcliffs:bronze_ingot'})
  event.remove({output: 'tmechworks:bronze_ingot'})

  event.remove({output: 'create:electrum_ingot'})
  event.remove({output: 'forestry:ingot_electrum'})
  event.remove({output: 'iceandfire:electrum_ingot'})
  event.remove({output: 'immersiveengineering:ingot_electrum'})
  event.remove({output: 'mekanism:ingot_electrum'})
  event.remove({output: 'occultism:electrum_ingot'})
  event.remove({output: 'projectred-core:electrum_ingot'})
  event.remove({output: 'tconstruct:electrum_ingot'})
  event.remove({output: 'cavesandcliffs:electrum_ingot'})
  event.remove({output: 'tmechworks:electrum_ingot'})

  event.remove({output: 'create:invar_ingot'})
  event.remove({output: 'forestry:ingot_invar'})
  event.remove({output: 'iceandfire:invar_ingot'})
  event.remove({output: 'immersiveengineering:ingot_invar'})
  event.remove({output: 'mekanism:ingot_invar'})
  event.remove({output: 'occultism:invar_ingot'})
  event.remove({output: 'projectred-core:invar_ingot'})
  event.remove({output: 'tconstruct:invar_ingot'})
  event.remove({output: 'cavesandcliffs:invar_ingot'})
  event.remove({output: 'tmechworks:invar_ingot'})

  event.remove({output: 'create:constantan_ingot'})
  event.remove({output: 'forestry:ingot_constantan'})
  event.remove({output: 'iceandfire:constantan_ingot'})
  event.remove({output: 'immersiveengineering:ingot_constantan'})
  event.remove({output: 'mekanism:ingot_constantan'})
  event.remove({output: 'occultism:constantan_ingot'})
  event.remove({output: 'projectred-core:constantan_ingot'})
  event.remove({output: 'tconstruct:constantan_ingot'})
  event.remove({output: 'cavesandcliffs:constantan_ingot'})
  event.remove({output: 'tmechworks:constantan_ingot'})

  event.remove({output: 'create:signalum_ingot'})
  event.remove({output: 'forestry:ingot_signalum'})
  event.remove({output: 'iceandfire:signalum_ingot'})
  event.remove({output: 'immersiveengineering:ingot_signalum'})
  event.remove({output: 'mekanism:ingot_signalum'})
  event.remove({output: 'occultism:signalum_ingot'})
  event.remove({output: 'projectred-core:signalum_ingot'})
  event.remove({output: 'tconstruct:signalum_ingot'})
  event.remove({output: 'cavesandcliffs:signalum_ingot'})
  event.remove({output: 'tmechworks:signalum_ingot'})

  event.remove({output: 'create:lumium_ingot'})
  event.remove({output: 'forestry:ingot_lumium'})
  event.remove({output: 'iceandfire:lumium_ingot'})
  event.remove({output: 'immersiveengineering:ingot_lumium'})
  event.remove({output: 'mekanism:ingot_lumium'})
  event.remove({output: 'occultism:lumium_ingot'})
  event.remove({output: 'projectred-core:lumium_ingot'})
  event.remove({output: 'tconstruct:lumium_ingot'})
  event.remove({output: 'cavesandcliffs:lumium_ingot'})
  event.remove({output: 'tmechworks:lumium_ingot'})

  event.remove({output: 'create:enderium_ingot'})
  event.remove({output: 'forestry:ingot_enderium'})
  event.remove({output: 'iceandfire:enderium_ingot'})
  event.remove({output: 'immersiveengineering:ingot_enderium'})
  event.remove({output: 'mekanism:ingot_enderium'})
  event.remove({output: 'occultism:enderium_ingot'})
  event.remove({output: 'projectred-core:enderium_ingot'})
  event.remove({output: 'tconstruct:enderium_ingot'})
  event.remove({output: 'cavesandcliffs:enderium_ingot'})
  event.remove({output: 'tmechworks:enderium_ingot'})



  //-------------------------------------------Plates-----------------------------------------



  event.remove({output: 'create:copper_plate'})
  event.remove({output: 'forestry:plate_copper'})
  event.remove({output: 'iceandfire:copper_plate'})
  event.remove({output: 'immersiveengineering:plate_copper'})
  event.remove({output: 'mekanism:plate_copper'})
  event.remove({output: 'occultism:copper_plate'})
  event.remove({output: 'projectred-core:copper_plate'})
  event.remove({output: 'tconstruct:copper_plate'})
  event.remove({output: 'cavesandcliffs:copper_plate'})
  event.remove({output: 'tmechworks:copper_plate'})

  event.remove({output: 'create:tin_plate'})
  event.remove({output: 'forestry:plate_tin'})
  event.remove({output: 'iceandfire:tin_plate'})
  event.remove({output: 'immersiveengineering:plate_tin'})
  event.remove({output: 'mekanism:plate_tin'})
  event.remove({output: 'occultism:tin_plate'})
  event.remove({output: 'projectred-core:tin_plate'})
  event.remove({output: 'tconstruct:tin_plate'})
  event.remove({output: 'cavesandcliffs:tin_plate'})
  event.remove({output: 'tmechworks:tin_plate'})

  event.remove({output: 'create:lead_plate'})
  event.remove({output: 'forestry:plate_lead'})
  event.remove({output: 'iceandfire:lead_plate'})
  event.remove({output: 'immersiveengineering:plate_lead'})
  event.remove({output: 'mekanism:plate_lead'})
  event.remove({output: 'occultism:lead_plate'})
  event.remove({output: 'projectred-core:lead_plate'})
  event.remove({output: 'tconstruct:lead_plate'})
  event.remove({output: 'cavesandcliffs:lead_plate'})
  event.remove({output: 'tmechworks:lead_plate'})

  event.remove({output: 'create:silver_plate'})
  event.remove({output: 'forestry:plate_silver'})
  event.remove({output: 'iceandfire:silver_plate'})
  event.remove({output: 'immersiveengineering:plate_silver'})
  event.remove({output: 'mekanism:plate_silver'})
  event.remove({output: 'occultism:silver_plate'})
  event.remove({output: 'projectred-core:silver_plate'})
  event.remove({output: 'tconstruct:silver_plate'})
  event.remove({output: 'cavesandcliffs:silver_plate'})
  event.remove({output: 'tmechworks:silver_plate'})

  event.remove({output: 'create:nickel_plate'})
event.remove({output: 'forestry:plate_nickel'})
event.remove({output: 'iceandfire:nickel_plate'})
event.remove({output: 'immersiveengineering:plate_nickel'})
event.remove({output: 'mekanism:plate_nickel'})
event.remove({output: 'occultism:nickel_plate'})
event.remove({output: 'projectred-core:nickel_plate'})
event.remove({output: 'tconstruct:nickel_plate'})
event.remove({output: 'cavesandcliffs:nickel_plate'})
event.remove({output: 'tmechworks:nickel_plate'})

event.remove({output: 'create:bronze_plate'})
event.remove({output: 'forestry:plate_bronze'})
event.remove({output: 'iceandfire:bronze_plate'})
event.remove({output: 'immersiveengineering:plate_bronze'})
event.remove({output: 'mekanism:plate_bronze'})
event.remove({output: 'occultism:bronze_plate'})
event.remove({output: 'projectred-core:bronze_plate'})
event.remove({output: 'tconstruct:bronze_plate'})
event.remove({output: 'cavesandcliffs:bronze_plate'})
event.remove({output: 'tmechworks:bronze_plate'})

event.remove({output: 'create:electrum_plate'})
event.remove({output: 'forestry:plate_electrum'})
event.remove({output: 'iceandfire:electrum_plate'})
event.remove({output: 'immersiveengineering:plate_electrum'})
event.remove({output: 'mekanism:plate_electrum'})
event.remove({output: 'occultism:electrum_plate'})
event.remove({output: 'projectred-core:electrum_plate'})
event.remove({output: 'tconstruct:electrum_plate'})
event.remove({output: 'cavesandcliffs:electrum_plate'})
event.remove({output: 'tmechworks:electrum_plate'})

event.remove({output: 'create:invar_plate'})
event.remove({output: 'forestry:plate_invar'})
event.remove({output: 'iceandfire:invar_plate'})
event.remove({output: 'immersiveengineering:plate_invar'})
event.remove({output: 'mekanism:plate_invar'})
event.remove({output: 'occultism:invar_plate'})
event.remove({output: 'projectred-core:invar_plate'})
event.remove({output: 'tconstruct:invar_plate'})
event.remove({output: 'cavesandcliffs:invar_plate'})
event.remove({output: 'tmechworks:invar_plate'})

event.remove({output: 'create:constantan_plate'})
event.remove({output: 'forestry:plate_constantan'})
event.remove({output: 'iceandfire:constantan_plate'})
event.remove({output: 'immersiveengineering:plate_constantan'})
event.remove({output: 'mekanism:plate_constantan'})
event.remove({output: 'occultism:constantan_plate'})
event.remove({output: 'projectred-core:constantan_plate'})
event.remove({output: 'tconstruct:constantan_plate'})
event.remove({output: 'cavesandcliffs:constantan_plate'})
event.remove({output: 'tmechworks:constantan_plate'})

event.remove({output: 'create:signalum_plate'})
event.remove({output: 'forestry:plate_signalum'})
event.remove({output: 'iceandfire:signalum_plate'})
event.remove({output: 'immersiveengineering:plate_signalum'})
event.remove({output: 'mekanism:plate_signalum'})
event.remove({output: 'occultism:signalum_plate'})
event.remove({output: 'projectred-core:signalum_plate'})
event.remove({output: 'tconstruct:signalum_plate'})
event.remove({output: 'cavesandcliffs:signalum_plate'})
event.remove({output: 'tmechworks:signalum_plate'})

event.remove({output: 'create:lumium_plate'})
event.remove({output: 'forestry:plate_lumium'})
event.remove({output: 'iceandfire:lumium_plate'})
event.remove({output: 'immersiveengineering:plate_lumium'})
event.remove({output: 'mekanism:plate_lumium'})
event.remove({output: 'occultism:lumium_plate'})
event.remove({output: 'projectred-core:lumium_plate'})
event.remove({output: 'tconstruct:lumium_plate'})
event.remove({output: 'cavesandcliffs:lumium_plate'})
event.remove({output: 'tmechworks:lumium_plate'})

event.remove({output: 'create:enderium_plate'})
event.remove({output: 'forestry:plate_enderium'})
event.remove({output: 'iceandfire:enderium_plate'})
event.remove({output: 'immersiveengineering:plate_enderium'})
event.remove({output: 'mekanism:plate_enderium'})
event.remove({output: 'occultism:enderium_plate'})
event.remove({output: 'projectred-core:enderium_plate'})
event.remove({output: 'tconstruct:enderium_plate'})
event.remove({output: 'cavesandcliffs:enderium_plate'})
event.remove({output: 'tmechworks:enderium_plate'})

event.remove({output: 'create:copper_dust'})
event.remove({output: 'forestry:dust_copper'})
event.remove({output: 'iceandfire:copper_dust'})
event.remove({output: 'immersiveengineering:dust_copper'})
event.remove({output: 'mekanism:dust_copper'})
event.remove({output: 'occultism:copper_dust'})
event.remove({output: 'projectred-core:copper_dust'})
event.remove({output: 'tconstruct:copper_dust'})
event.remove({output: 'cavesandcliffs:copper_dust'})
event.remove({output: 'tmechworks:copper_dust'})

event.remove({output: 'create:tin_dust'})
event.remove({output: 'forestry:dust_tin'})
event.remove({output: 'iceandfire:tin_dust'})
event.remove({output: 'immersiveengineering:dust_tin'})
event.remove({output: 'mekanism:dust_tin'})
event.remove({output: 'occultism:tin_dust'})
event.remove({output: 'projectred-core:tin_dust'})
event.remove({output: 'tconstruct:tin_dust'})
event.remove({output: 'cavesandcliffs:tin_dust'})
event.remove({output: 'tmechworks:tin_dust'})

event.remove({output: 'create:lead_dust'})
event.remove({output: 'forestry:dust_lead'})
event.remove({output: 'iceandfire:lead_dust'})
event.remove({output: 'immersiveengineering:dust_lead'})
event.remove({output: 'mekanism:dust_lead'})
event.remove({output: 'occultism:lead_dust'})
event.remove({output: 'projectred-core:lead_dust'})
event.remove({output: 'tconstruct:lead_dust'})
event.remove({output: 'cavesandcliffs:lead_dust'})
event.remove({output: 'tmechworks:lead_dust'})

event.remove({output: 'create:silver_dust'})
event.remove({output: 'forestry:dust_silver'})
event.remove({output: 'iceandfire:silver_dust'})
event.remove({output: 'immersiveengineering:dust_silver'})
event.remove({output: 'mekanism:dust_silver'})
event.remove({output: 'occultism:silver_dust'})
event.remove({output: 'projectred-core:silver_dust'})
event.remove({output: 'tconstruct:silver_dust'})
event.remove({output: 'cavesandcliffs:silver_dust'})
event.remove({output: 'tmechworks:silver_dust'})

event.remove({output: 'create:nickel_dust'})
event.remove({output: 'forestry:dust_nickel'})
event.remove({output: 'iceandfire:nickel_dust'})
event.remove({output: 'immersiveengineering:dust_nickel'})
event.remove({output: 'mekanism:dust_nickel'})
event.remove({output: 'occultism:nickel_dust'})
event.remove({output: 'projectred-core:nickel_dust'})
event.remove({output: 'tconstruct:nickel_dust'})
event.remove({output: 'cavesandcliffs:nickel_dust'})
event.remove({output: 'tmechworks:nickel_dust'})

event.remove({output: 'create:bronze_dust'})
event.remove({output: 'forestry:dust_bronze'})
event.remove({output: 'iceandfire:bronze_dust'})
event.remove({output: 'immersiveengineering:dust_bronze'})
event.remove({output: 'mekanism:dust_bronze'})
event.remove({output: 'occultism:bronze_dust'})
event.remove({output: 'projectred-core:bronze_dust'})
event.remove({output: 'tconstruct:bronze_dust'})
event.remove({output: 'cavesandcliffs:bronze_dust'})
event.remove({output: 'tmechworks:bronze_dust'})

event.remove({output: 'create:electrum_dust'})
event.remove({output: 'forestry:dust_electrum'})
event.remove({output: 'iceandfire:electrum_dust'})
event.remove({output: 'immersiveengineering:dust_electrum'})
event.remove({output: 'mekanism:dust_electrum'})
event.remove({output: 'occultism:electrum_dust'})
event.remove({output: 'projectred-core:electrum_dust'})
event.remove({output: 'tconstruct:electrum_dust'})
event.remove({output: 'cavesandcliffs:electrum_dust'})
event.remove({output: 'tmechworks:electrum_dust'})

event.remove({output: 'create:invar_dust'})
event.remove({output: 'forestry:dust_invar'})
event.remove({output: 'iceandfire:invar_dust'})
event.remove({output: 'immersiveengineering:dust_invar'})
event.remove({output: 'mekanism:dust_invar'})
event.remove({output: 'occultism:invar_dust'})
event.remove({output: 'projectred-core:invar_dust'})
event.remove({output: 'tconstruct:invar_dust'})
event.remove({output: 'cavesandcliffs:invar_dust'})
event.remove({output: 'tmechworks:invar_dust'})

event.remove({output: 'create:constantan_dust'})
event.remove({output: 'forestry:dust_constantan'})
event.remove({output: 'iceandfire:constantan_dust'})
event.remove({output: 'immersiveengineering:dust_constantan'})
event.remove({output: 'mekanism:dust_constantan'})
event.remove({output: 'occultism:constantan_dust'})
event.remove({output: 'projectred-core:constantan_dust'})
event.remove({output: 'tconstruct:constantan_dust'})
event.remove({output: 'cavesandcliffs:constantan_dust'})
event.remove({output: 'tmechworks:constantan_dust'})

event.remove({output: 'create:signalum_dust'})
event.remove({output: 'forestry:dust_signalum'})
event.remove({output: 'iceandfire:signalum_dust'})
event.remove({output: 'immersiveengineering:dust_signalum'})
event.remove({output: 'mekanism:dust_signalum'})
event.remove({output: 'occultism:signalum_dust'})
event.remove({output: 'projectred-core:signalum_dust'})
event.remove({output: 'tconstruct:signalum_dust'})
event.remove({output: 'cavesandcliffs:signalum_dust'})
event.remove({output: 'tmechworks:signalum_dust'})

event.remove({output: 'create:lumium_dust'})
event.remove({output: 'forestry:dust_lumium'})
event.remove({output: 'iceandfire:lumium_dust'})
event.remove({output: 'immersiveengineering:dust_lumium'})
event.remove({output: 'mekanism:dust_lumium'})
event.remove({output: 'occultism:lumium_dust'})
event.remove({output: 'projectred-core:lumium_dust'})
event.remove({output: 'tconstruct:lumium_dust'})
event.remove({output: 'cavesandcliffs:lumium_dust'})
event.remove({output: 'tmechworks:lumium_dust'})

event.remove({output: 'create:enderium_dust'})
event.remove({output: 'forestry:dust_enderium'})
event.remove({output: 'iceandfire:enderium_dust'})
event.remove({output: 'immersiveengineering:dust_enderium'})
event.remove({output: 'mekanism:dust_enderium'})
event.remove({output: 'occultism:enderium_dust'})
event.remove({output: 'projectred-core:enderium_dust'})
event.remove({output: 'tconstruct:enderium_dust'})
event.remove({output: 'cavesandcliffs:enderium_dust'})
event.remove({output: 'tmechworks:enderium_dust'})

event.remove({output: 'create:copper_gear'})
event.remove({output: 'forestry:gear_copper'})
event.remove({output: 'iceandfire:copper_gear'})
event.remove({output: 'immersiveengineering:gear_copper'})
event.remove({output: 'mekanism:gear_copper'})
event.remove({output: 'occultism:copper_gear'})
event.remove({output: 'projectred-core:copper_gear'})
event.remove({output: 'tconstruct:copper_gear'})
event.remove({output: 'cavesandcliffs:copper_gear'})
event.remove({output: 'tmechworks:copper_gear'})

event.remove({output: 'create:tin_gear'})
event.remove({output: 'forestry:gear_tin'})
event.remove({output: 'iceandfire:tin_gear'})
event.remove({output: 'immersiveengineering:gear_tin'})
event.remove({output: 'mekanism:gear_tin'})
event.remove({output: 'occultism:tin_gear'})
event.remove({output: 'projectred-core:tin_gear'})
event.remove({output: 'tconstruct:tin_gear'})
event.remove({output: 'cavesandcliffs:tin_gear'})

event.remove({output: 'create:lead_gear'})
event.remove({output: 'forestry:gear_lead'})
event.remove({output: 'iceandfire:lead_gear'})
event.remove({output: 'immersiveengineering:gear_lead'})
event.remove({output: 'mekanism:gear_lead'})
event.remove({output: 'occultism:lead_gear'})
event.remove({output: 'projectred-core:lead_gear'})
event.remove({output: 'tconstruct:lead_gear'})
event.remove({output: 'cavesandcliffs:lead_gear'})
event.remove({output: 'tmechworks:lead_gear'})

event.remove({output: 'create:silver_gear'})
event.remove({output: 'forestry:gear_silver'})
event.remove({output: 'iceandfire:silver_gear'})
event.remove({output: 'immersiveengineering:gear_silver'})
event.remove({output: 'mekanism:gear_silver'})
event.remove({output: 'occultism:silver_gear'})
event.remove({output: 'projectred-core:silver_gear'})
event.remove({output: 'tconstruct:silver_gear'})
event.remove({output: 'cavesandcliffs:silver_gear'})
event.remove({output: 'tmechworks:silver_gear'})

event.remove({output: 'create:nickel_gear'})
event.remove({output: 'forestry:gear_nickel'})
event.remove({output: 'iceandfire:nickel_gear'})
event.remove({output: 'immersiveengineering:gear_nickel'})
event.remove({output: 'mekanism:gear_nickel'})
event.remove({output: 'occultism:nickel_gear'})
event.remove({output: 'projectred-core:nickel_gear'})
event.remove({output: 'tconstruct:nickel_gear'})
event.remove({output: 'cavesandcliffs:nickel_gear'})
event.remove({output: 'tmechworks:nickel_gear'})

event.remove({output: 'create:bronze_gear'})
event.remove({output: 'forestry:gear_bronze'})
event.remove({output: 'iceandfire:bronze_gear'})
event.remove({output: 'immersiveengineering:gear_bronze'})
event.remove({output: 'mekanism:gear_bronze'})
event.remove({output: 'occultism:bronze_gear'})
event.remove({output: 'projectred-core:bronze_gear'})
event.remove({output: 'tconstruct:bronze_gear'})
event.remove({output: 'cavesandcliffs:bronze_gear'})
event.remove({output: 'tmechworks:bronze_gear'})

event.remove({output: 'create:electrum_gear'})
event.remove({output: 'forestry:gear_electrum'})
event.remove({output: 'iceandfire:electrum_gear'})
event.remove({output: 'immersiveengineering:gear_electrum'})
event.remove({output: 'mekanism:gear_electrum'})
event.remove({output: 'occultism:electrum_gear'})
event.remove({output: 'projectred-core:electrum_gear'})
event.remove({output: 'tconstruct:electrum_gear'})
event.remove({output: 'cavesandcliffs:electrum_gear'})
event.remove({output: 'tmechworks:electrum_gear'})

event.remove({output: 'create:invar_gear'})
event.remove({output: 'forestry:gear_invar'})
event.remove({output: 'iceandfire:invar_gear'})
event.remove({output: 'immersiveengineering:gear_invar'})
event.remove({output: 'mekanism:gear_invar'})
event.remove({output: 'occultism:invar_gear'})
event.remove({output: 'projectred-core:invar_gear'})
event.remove({output: 'tconstruct:invar_gear'})
event.remove({output: 'cavesandcliffs:invar_gear'})
event.remove({output: 'tmechworks:invar_gear'})

event.remove({output: 'create:constantan_gear'})
event.remove({output: 'forestry:gear_constantan'})
event.remove({output: 'iceandfire:constantan_gear'})
event.remove({output: 'immersiveengineering:gear_constantan'})
event.remove({output: 'mekanism:gear_constantan'})
event.remove({output: 'occultism:constantan_gear'})
event.remove({output: 'projectred-core:constantan_gear'})
event.remove({output: 'tconstruct:constantan_gear'})
event.remove({output: 'cavesandcliffs:constantan_gear'})
event.remove({output: 'tmechworks:constantan_gear'})

event.remove({output: 'create:signalum_gear'})
event.remove({output: 'forestry:gear_signalum'})
event.remove({output: 'iceandfire:signalum_gear'})
event.remove({output: 'immersiveengineering:gear_signalum'})
event.remove({output: 'mekanism:gear_signalum'})
event.remove({output: 'occultism:signalum_gear'})
event.remove({output: 'projectred-core:signalum_gear'})
event.remove({output: 'tconstruct:signalum_gear'})
event.remove({output: 'cavesandcliffs:signalum_gear'})
event.remove({output: 'tmechworks:signalum_gear'})

event.remove({output: 'create:lumium_gear'})
event.remove({output: 'forestry:gear_lumium'})
event.remove({output: 'iceandfire:lumium_gear'})
event.remove({output: 'immersiveengineering:gear_lumium'})
event.remove({output: 'mekanism:gear_lumium'})
event.remove({output: 'occultism:lumium_gear'})
event.remove({output: 'projectred-core:lumium_gear'})
event.remove({output: 'tconstruct:lumium_gear'})
event.remove({output: 'cavesandcliffs:lumium_gear'})
event.remove({output: 'tmechworks:lumium_gear'})

event.remove({output: 'create:enderium_gear'})
event.remove({output: 'forestry:gear_enderium'})
event.remove({output: 'iceandfire:enderium_gear'})
event.remove({output: 'immersiveengineering:gear_enderium'})
event.remove({output: 'mekanism:gear_enderium'})
event.remove({output: 'occultism:enderium_gear'})
event.remove({output: 'projectred-core:enderium_gear'})
event.remove({output: 'tconstruct:enderium_gear'})
event.remove({output: 'cavesandcliffs:enderium_gear'})
event.remove({output: 'tmechworks:enderium_gear'})

event.remove({output: 'mekanism:dust_steel'})
event.remove({output: 'mekanism:ingot_steel'})
event.remove({output: 'mekanism:nugget_steel'})
event.remove({output: 'mekanism:block_steel'})
event.remove({output: 'mekanism:dust_uranium'})
event.remove({output: 'mekanism:ingot_uranium'})
event.remove({output: 'mekanism:nugget_uranium'})
event.remove({output: 'mekanism:block_uranium'})

event.remove({output: 'create:copper_nugget'}) 
event.remove({output: 'iceandfire:copper_nugget'})
event.remove({output: 'immersiveengineering:nugget_copper'})
event.remove({output: 'mekanism:nugget_copper'}) 
event.remove({output: 'occultism:copper_nugget'}) 
event.remove({output: 'tconstruct:copper_nugget'})
event.remove({output: 'tmechworks:copper_nugget'})
event.remove({output: 'boss_tools:copper_nugget'})
event.remove({output: 'mekanism:nugget_copper'})

event.remove({output: 'create:tin_nugget'}) 
event.remove({output: 'iceandfire:tin_nugget'})
event.remove({output: 'immersiveengineering:nugget_tin'})
event.remove({output: 'mekanism:nugget_tin'}) 
event.remove({output: 'occultism:tin_nugget'}) 
event.remove({output: 'tconstruct:tin_nugget'})
event.remove({output: 'tmechworks:tin_nugget'})
event.remove({output: 'boss_tools:tin_nugget'})
event.remove({output: 'mekanism:nugget_tin'})

event.remove({output: 'create:lead_nugget'}) 
event.remove({output: 'iceandfire:lead_nugget'})
event.remove({output: 'immersiveengineering:nugget_lead'})
event.remove({output: 'mekanism:nugget_lead'}) 
event.remove({output: 'occultism:lead_nugget'}) 
event.remove({output: 'tconstruct:lead_nugget'})
event.remove({output: 'tmechworks:lead_nugget'})
event.remove({output: 'boss_tools:lead_nugget'})
event.remove({output: 'mekanism:nugget_lead'})

event.remove({output: 'create:silver_nugget'}) 
event.remove({output: 'iceandfire:silver_nugget'})
event.remove({output: 'immersiveengineering:nugget_silver'})
event.remove({output: 'mekanism:nugget_silver'}) 
event.remove({output: 'occultism:silver_nugget'}) 
event.remove({output: 'tconstruct:silver_nugget'})
event.remove({output: 'tmechworks:silver_nugget'})
event.remove({output: 'boss_tools:silver_nugget'})
event.remove({output: 'mekanism:nugget_silver'})

event.remove({output: 'create:nickel_nugget'}) 
event.remove({output: 'iceandfire:nickel_nugget'})
event.remove({output: 'immersiveengineering:nugget_nickel'})
event.remove({output: 'mekanism:nugget_nickel'}) 
event.remove({output: 'occultism:nickel_nugget'}) 
event.remove({output: 'tconstruct:nickel_nugget'})
event.remove({output: 'tmechworks:nickel_nugget'})
event.remove({output: 'boss_tools:nickel_nugget'})
event.remove({output: 'mekanism:nugget_nickel'})

event.remove({output: 'create:bronze_nugget'}) 
event.remove({output: 'iceandfire:bronze_nugget'})
event.remove({output: 'immersiveengineering:nugget_bronze'})
event.remove({output: 'mekanism:nugget_bronze'}) 
event.remove({output: 'occultism:bronze_nugget'}) 
event.remove({output: 'tconstruct:bronze_nugget'})
event.remove({output: 'tmechworks:bronze_nugget'})
event.remove({output: 'boss_tools:bronze_nugget'})
event.remove({output: 'mekanism:nugget_bronze'})

event.remove({output: 'create:electrum_nugget'}) 
event.remove({output: 'iceandfire:electrum_nugget'})
event.remove({output: 'immersiveengineering:nugget_electrum'})
event.remove({output: 'mekanism:nugget_electrum'}) 
event.remove({output: 'occultism:electrum_nugget'}) 
event.remove({output: 'tconstruct:electrum_nugget'})
event.remove({output: 'tmechworks:electrum_nugget'})
event.remove({output: 'boss_tools:electrum_nugget'})
event.remove({output: 'mekanism:nugget_electrum'})

event.remove({output: 'create:invar_nugget'}) 
event.remove({output: 'iceandfire:invar_nugget'})
event.remove({output: 'immersiveengineering:nugget_invar'})
event.remove({output: 'mekanism:nugget_invar'}) 
event.remove({output: 'occultism:invar_nugget'}) 
event.remove({output: 'tconstruct:invar_nugget'})
event.remove({output: 'tmechworks:invar_nugget'})
event.remove({output: 'boss_tools:invar_nugget'})
event.remove({output: 'mekanism:nugget_invar'})

event.remove({output: 'create:constantan_nugget'}) 
event.remove({output: 'iceandfire:constantan_nugget'})
event.remove({output: 'immersiveengineering:nugget_constantan'})
event.remove({output: 'mekanism:nugget_constantan'}) 
event.remove({output: 'occultism:constantan_nugget'}) 
event.remove({output: 'tconstruct:constantan_nugget'})
event.remove({output: 'tmechworks:constantan_nugget'})
event.remove({output: 'boss_tools:constantan_nugget'})
event.remove({output: 'mekanism:nugget_constantan'})

event.remove({output: 'create:lumium_nugget'}) 
event.remove({output: 'iceandfire:lumium_nugget'})
event.remove({output: 'immersiveengineering:nugget_lumium'})
event.remove({output: 'mekanism:nugget_lumium'}) 
event.remove({output: 'occultism:lumium_nugget'}) 
event.remove({output: 'tconstruct:lumium_nugget'})
event.remove({output: 'tmechworks:lumium_nugget'})
event.remove({output: 'boss_tools:lumium_nugget'})
event.remove({output: 'mekanism:nugget_lumium'})

event.remove({output: 'create:signalum_nugget'}) 
event.remove({output: 'iceandfire:signalum_nugget'})
event.remove({output: 'immersiveengineering:nugget_signalum'})
event.remove({output: 'mekanism:nugget_signalum'}) 
event.remove({output: 'occultism:signalum_nugget'}) 
event.remove({output: 'tconstruct:signalum_nugget'})
event.remove({output: 'tmechworks:signalum_nugget'})
event.remove({output: 'boss_tools:signalum_nugget'})
event.remove({output: 'mekanism:nugget_signalum'})

event.remove({output: 'create:enderium_nugget'}) 
event.remove({output: 'iceandfire:enderium_nugget'})
event.remove({output: 'immersiveengineering:nugget_enderium'})
event.remove({output: 'mekanism:nugget_enderium'}) 
event.remove({output: 'occultism:enderium_nugget'}) 
event.remove({output: 'tconstruct:enderium_nugget'})
event.remove({output: 'tmechworks:enderium_nugget'})
event.remove({output: 'boss_tools:enderium_nugget'})
event.remove({output: 'mekanism:nugget_enderium'})

event.remove({output: 'boss_tools:steel_nugget'})
event.remove({output: 'mekanism:nugget_steel'})
event.remove({output: 'boss_tools:uranium_nugget'})
event.remove({output: 'mekanism:nugget_uranium'})

event.remove({output: 'create:copper_block'}) 
event.remove({output: 'forestry:resource_storage_copper'}) 
event.remove({output: 'immersiveengineering:storage_copper'}) 
event.remove({output: 'occultism:copper_block'}) 
event.remove({output: 'tconstruct:copper_block'}) 
event.remove({output: 'cavesandcliffs:copper_block'}) 
event.remove({output: 'tmechworks:copper_block'})

event.remove({output: 'create:tin_block'}) 
event.remove({output: 'forestry:resource_storage_tin'}) 
event.remove({output: 'immersiveengineering:storage_tin'}) 
event.remove({output: 'occultism:tin_block'}) 
event.remove({output: 'tconstruct:tin_block'}) 
event.remove({output: 'cavesandcliffs:tin_block'}) 
event.remove({output: 'tmechworks:tin_block'})

event.remove({output: 'create:lead_block'}) 
event.remove({output: 'forestry:resource_storage_lead'}) 
event.remove({output: 'immersiveengineering:storage_lead'}) 
event.remove({output: 'occultism:lead_block'}) 
event.remove({output: 'tconstruct:lead_block'}) 
event.remove({output: 'cavesandcliffs:lead_block'}) 
event.remove({output: 'tmechworks:lead_block'})

event.remove({output: 'create:silver_block'}) 
event.remove({output: 'forestry:resource_storage_silver'}) 
event.remove({output: 'immersiveengineering:storage_silver'}) 
event.remove({output: 'occultism:silver_block'}) 
event.remove({output: 'tconstruct:silver_block'}) 
event.remove({output: 'cavesandcliffs:silver_block'}) 
event.remove({output: 'tmechworks:silver_block'})

event.remove({output: 'create:electrum_block'}) 
event.remove({output: 'forestry:resource_storage_electrum'}) 
event.remove({output: 'immersiveengineering:storage_electrum'}) 
event.remove({output: 'occultism:electrum_block'}) 
event.remove({output: 'tconstruct:electrum_block'}) 
event.remove({output: 'cavesandcliffs:electrum_block'}) 
event.remove({output: 'tmechworks:electrum_block'})

event.remove({output: 'create:invar_block'}) 
event.remove({output: 'forestry:resource_storage_invar'}) 
event.remove({output: 'immersiveengineering:storage_invar'}) 
event.remove({output: 'occultism:invar_block'}) 
event.remove({output: 'tconstruct:invar_block'}) 
event.remove({output: 'cavesandcliffs:invar_block'}) 
event.remove({output: 'tmechworks:invar_block'})

event.remove({output: 'create:nickel_block'}) 
event.remove({output: 'forestry:resource_storage_nickel'}) 
event.remove({output: 'immersiveengineering:storage_nickel'}) 
event.remove({output: 'occultism:nickel_block'}) 
event.remove({output: 'tconstruct:nickel_block'}) 
event.remove({output: 'cavesandcliffs:nickel_block'}) 
event.remove({output: 'tmechworks:nickel_block'})

event.remove({output: 'create:constantan_block'}) 
event.remove({output: 'forestry:resource_storage_constantan'}) 
event.remove({output: 'immersiveengineering:storage_constantan'}) 
event.remove({output: 'occultism:constantan_block'}) 
event.remove({output: 'tconstruct:constantan_block'}) 
event.remove({output: 'cavesandcliffs:constantan_block'}) 
event.remove({output: 'tmechworks:constantan_block'})

event.remove({output: 'create:signalum_block'}) 
event.remove({output: 'forestry:resource_storage_signalum'}) 
event.remove({output: 'immersiveengineering:storage_signalum'}) 
event.remove({output: 'occultism:signalum_block'}) 
event.remove({output: 'tconstruct:signalum_block'}) 
event.remove({output: 'cavesandcliffs:signalum_block'}) 
event.remove({output: 'tmechworks:signalum_block'})

event.remove({output: 'create:lumium_block'}) 
event.remove({output: 'forestry:resource_storage_lumium'}) 
event.remove({output: 'immersiveengineering:storage_lumium'}) 
event.remove({output: 'occultism:lumium_block'}) 
event.remove({output: 'tconstruct:lumium_block'}) 
event.remove({output: 'cavesandcliffs:lumium_block'}) 
event.remove({output: 'tmechworks:lumium_block'})

event.remove({output: 'create:enderium_block'}) 
event.remove({output: 'forestry:resource_storage_enderium'}) 
event.remove({output: 'immersiveengineering:storage_enderium'}) 
event.remove({output: 'occultism:enderium_block'}) 
event.remove({output: 'tconstruct:enderium_block'}) 
event.remove({output: 'cavesandcliffs:enderium_block'}) 
event.remove({output: 'tmechworks:enderium_block'})

event.remove({output: 'boss_tools:steel_block'}) 
event.remove({output: 'mekanism:block_steel'})
event.remove({output: 'boss_tools:uranium_block'}) 
event.remove({output: 'mekanism:uranium_steel'})

event.remove({output: 'mekanism:block_tin'}) 
event.remove({output: 'mekanism:block_lead'}) 
event.remove({output: 'mekanism:block_bronze'}) 
event.remove({output: 'iceandfire:copper_block'}) 
event.remove({output: 'mekanism:block_copper'})

event.remove({output: 'occultism:iron_dust'})
event.remove({output: 'mekanism:dust_iron'})
event.remove({output: 'immersiveengineering:dust_iron'})
event.remove({output: 'occultism:gold_dust'})
event.remove({output: 'mekanism:dust_gold'})
event.remove({output: 'immersiveengineering:dust_gold'})

event.remove({output: 'titanium:diamond_gear'})
event.remove({output: 'titanium:iron_gear'})
event.remove({output: 'titanium:gold_gear'})

event.remove({output: 'immersiveengineering:plate_iron'})
event.remove({output: 'boss_tools:iron_plate'})
event.remove({output: 'create:iron_sheet'})
event.remove({output: 'immersiveengineering:plate_gold'})
event.remove({output: 'boss_tools:gold_plate'})
event.remove({output: 'create:golden_sheet'})
event.remove({output: 'immersiveengineering:plate_tin'})
event.remove({output: 'boss_tools:tin_plate'})
event.remove({output: 'create:tin_sheet'})
event.remove({output: 'immersiveengineering:plate_silver'})

event.remove({output: 'boss_tools:silver_plate'})
event.remove({output: 'create:silver_sheet'})
event.remove({output: 'immersiveengineering:plate_lead'})

event.remove({output: 'boss_tools:lead_plate'})
event.remove({output: 'create:lead_sheet'})
event.remove({output: 'immersiveengineering:plate_silver'})

event.remove({output: 'boss_tools:silver_plate'})
event.remove({output: 'create:silver_sheet'})
event.remove({output: 'immersiveengineering:plate_nickel'})

event.remove({output: 'boss_tools:nickel_plate'})
event.remove({output: 'create:nickel_sheet'})
event.remove({output: 'immersiveengineering:plate_bronze'})

event.remove({output: 'boss_tools:bronze_plate'})
event.remove({output: 'create:bronze_sheet'})
event.remove({output: 'immersiveengineering:plate_electrum'})

event.remove({output: 'boss_tools:electrum_plate'})
event.remove({output: 'create:electrum_sheet'})
event.remove({output: 'immersiveengineering:plate_invar'})

event.remove({output: 'boss_tools:invar_plate'})
event.remove({output: 'create:invar_sheet'})
event.remove({output: 'immersiveengineering:plate_constantan'})

event.remove({output: 'boss_tools:constantan_plate'})
event.remove({output: 'create:constantan_sheet'})
event.remove({output: 'immersiveengineering:plate_signalum'})

event.remove({output: 'boss_tools:signalum_plate'})
event.remove({output: 'create:signalum_sheet'})
event.remove({output: 'immersiveengineering:plate_lumium'})

event.remove({output: 'boss_tools:lumium_plate'})
event.remove({output: 'create:lumium_sheet'})
event.remove({output: 'immersiveengineering:plate_enderium'})

event.remove({output: 'boss_tools:enderium_plate'})
event.remove({output: 'create:enderium_sheet'})
event.remove({output: 'create:brass_sheet'})
event.remove({output: 'createaddition:zinc_sheet'})
event.remove({output: 'miniutilities:ender_dust'})
event.remove({output: 'immersiveengineering:dust_sulfur'})
event.remove({output: 'immersiveengineering:dust_saltpeter'})
event.remove({output: 'immersiveengineering:dust_wood'})
event.remove({output: 'eidolon:lead_ingot'})
})