
[general]
	#The material blacklist of this module.
	materialBlacklist = []

[recipes]
	#The materials that should not have grinding recipes added.
	toDustMaterialBlacklist = []
	#The materials that should not have compacting recipes added.
	toPlateMaterialBlacklist = []

