// priority: 1000

// Block
onEvent('block.registry', event => {
	event.create('ibpdx:neptune_dungeon_floor').material('stone').hardness(1.0).displayName('Neptune Dungeon Floor')
	event.create('ibpdx:circuit_case').material('stone').hardness(1.0).displayName('Circuit Case')
	event.create('ibpdx:space_glass').material('glass').hardness(1.0).displayName('Space Glass').defaultTranslucent()
	event.create('ibpdx:terra_glass').material('glass').hardness(1.0).displayName('Terra Glass').defaultTranslucent()
	event.create('ibpdx:space_trophy').material('stone').hardness(1.0).displayName('Space Trophy')
	event.create('ibpdx:omni_ore').material('stone').hardness(1.0).displayName('Omni Ore')
	event.create('ibpdx:ultimate_tech_block').material('stone').hardness(1.0).displayName('Ultimate Tech Block')
	event.create('ibpdx:ultimate_magic_block').material('stone').hardness(1.0).displayName('Ultimate Magic Block')
	event.create('ibpdx:blockcasing_awakened').material('stone').hardness(1.0).displayName('Awakened Draconium Casing')
	event.create('ibpdx:blockcasing_bedrock').material('stone').hardness(1.0).displayName('Bedrock Casing')
	event.create('ibpdx:blockcasing_black_quartz').material('stone').hardness(1.0).displayName('Black Quartz Casing')
	event.create('ibpdx:blockcasing_duskstone').material('stone').hardness(1.0).displayName('Duskstone Casing')
	event.create('ibpdx:blockcasing_elementium').material('stone').hardness(1.0).displayName('Elementium Casing')
	event.create('ibpdx:blockcasing_empowered_diamond').material('stone').hardness(1.0).displayName('Infused Diamond Casing')
	event.create('ibpdx:blockcasing_empowered_steel').material('stone').hardness(1.0).displayName('Empowered Steel Casing')
	event.create('ibpdx:blockcasing_enderium').material('stone').hardness(1.0).displayName('Enderium Casing')
	event.create('ibpdx:blockcasing_livingrock').material('stone').hardness(1.0).displayName('Livingrock Casing')
	event.create('ibpdx:blockcasing_refined_glowstone').material('stone').hardness(1.0).displayName('Refined Glowstone Casing')
	event.create('ibpdx:blockcasing_starmetal').material('stone').hardness(1.0).displayName('Starmetal Casing')
    event.create('ibpdx:blockcasing_steel').material('stone').hardness(1.0).displayName('Steel Casing')
    event.create('ibpdx:blockcasing_manasteel').material('stone').hardness(1.0).displayName('Manasteel Casing')
    event.create('ibpdx:blockcasing_terrasteel').material('stone').hardness(1.0).displayName('Terrasteel Casing')
	event.create('ibpdx:singular_speed_gearbox').material('stone').hardness(1.0).displayName('Singular Torsion Speed Gearbox')
	event.create('ibpdx:singular_double_gearbox').material('stone').hardness(1.0).displayName('Singular Torsion Double Gearbox')
	event.create('ibpdx:singular_power_gearbox').material('stone').hardness(1.0).displayName('Singular Torsion Power Gearbox')
	event.create('ibpdx:simulation_core').material('stone').hardness(1.0).displayName('Simulation Core')
	event.create('ibpdx:life_infused_cooler').material('stone').hardness(1.0).displayName('Life Infused Cooler')
	event.create('ibpdx:circuit_shell').material('stone').hardness(1.0).displayName('Circuit Shell')
	event.create('ibpdx:mixed_brick_block').material('stone').hardness(1.0).displayName('Block Of Mixed Brick')
	event.create('ibpdx:molten_gold_casing').material('stone').hardness(1.0).displayName('Molten Gold Casing')
	event.create('ibpdx:iron_casing').material('metal').hardness(1.0).displayName('Iron Casing')
	event.create('ibpdx:speed_gearbox').material('metal').hardness(1.0).displayName('Speed Gearbox')
	event.create('ibpdx:double_gearbox').material('metal').hardness(1.0).displayName('Double Gearbox')
	event.create('ibpdx:power_gearbox').material('metal').hardness(1.0).displayName('Power Gearbox')
	event.create('ibpdx:ethetic_quartz').material('stone').hardness(1.0).displayName('Ethetic Quartz')
	event.create('ibpdx:duplication_core').material('stone').hardness(1.0).displayName('Duplication Core')
	event.create('ibpdx:stainless_steel_block').material('metal').hardness(1.0).displayName('Stainless Steel Block')
	event.create('ibpdx:stainless_steel_casing').material('metal').hardness(1.0).displayName('Stainless Steel Casing')
	event.create('ibpdx:hot_cooking_plate').material('metal').hardness(1.0).displayName('Hot Cooking Plate').texture('north', 'ibpdx:block/hot_cooking_platesides').texture('south', 'ibpdx:block/hot_cooking_platesides').texture('east', 'ibpdx:block/hot_cooking_platesides').texture('west', 'ibpdx:block/hot_cooking_platesides')
	event.create('ibpdx:cool_cooking_plate').material('metal').hardness(1.0).displayName('Cool Cooking Plate').texture('north', 'ibpdx:block/cool_cooking_platesides').texture('south', 'ibpdx:block/cool_cooking_platesides').texture('east', 'ibpdx:block/cool_cooking_platesides').texture('west', 'ibpdx:block/cool_cooking_platesides')
	event.create('ibpdx:ashen_charcoal').material('dirt').hardness(0.5).displayName('Ashen Charcoal')
	event.create('ibpdx:bog_earth').material('dirt').hardness(0.5).displayName('Bog Earth')
	event.create('ibpdx:peat_bog').material('dirt').hardness(0.5).displayName('Peat Bog')
	event.create('ibpdx:azurine_moon_stone').material('stone').hardness(1.0).displayName('Azurine Moon Stone')
	event.create('ibpdx:chalky_moon_stone').material('stone').hardness(1.0).displayName('Chalky Moon Stone')
	event.create('ibpdx:verdant_moon_stone').material('stone').hardness(1.0).displayName('Verdant Moon Stone')
	event.create('ibpdx:carmine_moon_stone').material('stone').hardness(1.0).displayName('Carmine Moon Stone')
	event.create('ibpdx:ultramarine_moon_stone').material('stone').hardness(1.0).displayName('Ultramarine Moon Stone')
	event.create('ibpdx:umbral_moon_stone').material('stone').hardness(1.0).displayName('Umbral Moon Stone')
	event.create('ibpdx:lead_plating').material('stone').hardness(1.0).displayName('Lead Plating')
	event.create('ibpdx:iridium_block').material('metal').hardness(1.0).displayName('Iridium Block')
})
