// priority: 1000

// Fluid
onEvent('fluid.registry', event => {
	// Default Namespace for Pyrotheum and Cryotheum, bcause Powah isn't playing nice
	event.create('molten_pyrotheum').textureThick(0xf7db3a).bucketColor(0xf7db3a).displayName('Molten Pyrotheum')
	event.create('molten_cryotheum').textureThick(0x43f4f7).bucketColor(0x43f4f7).displayName('Molten Cryotheum')


	event.create('ibpdx:molten_petrotheum').textureThick(0x1a1310).bucketColor(0x1a1310).displayName('Molten Petrotheum')
	event.create('ibpdx:molten_aerotheum').textureThick(0xc8da94).bucketColor(0xc8da94).displayName('Molten Aerotheum')
    event.create('ibpdx:iron_slurry').textureThick(0xd1d1d1).bucketColor(0xd1d1d1).displayName('Iron Slurry')
    event.create('ibpdx:gold_slurry').textureThick(0xfcdc4c).bucketColor(0xfcdc4c).displayName('Gold Slurry')
    event.create('ibpdx:lead_slurry').textureThick(0x94a9db).bucketColor(0x94a9db).displayName('Lead Slurry')
    event.create('ibpdx:silver_slurry').textureThick(0xe4f2f7).bucketColor(0xe4f2f7).displayName('Silver Slurry')
    event.create('ibpdx:tin_slurry').textureThick(0xacccd4).bucketColor(0xacccd4).displayName('Tin Slurry')
    event.create('ibpdx:copper_slurry').textureThick(0xf4b434).bucketColor(0xf4b434).displayName('Copper Slurry')
	event.create('ibpdx:fusion_waste').textureThick(0x092e08).bucketColor(0x092e08).displayName('Fusion Waste')
	event.create('ibpdx:empowered_oil').textureThin(0xAC0E0E).bucketColor(0xAC0E0E).displayName('Empowered Oil')
	event.create('ibpdx:crystallized_oil').textureThin(0xCE3535).bucketColor(0xCE3535).displayName('Crystallized Oil')
	event.create('ibpdx:carbonic_acid').textureThin(0x111111).bucketColor(0x111111).displayName('Carbonic Acid')
    event.create('ibpdx:molten_chromium').textureThick(0xe4f2f7).bucketColor(0xe4f2f7).displayName('Molten Chromium')
    event.create('ibpdx:energized_speed_potion').textureThin(0x8DD4E4).bucketColor(0x8DD4E4).displayName('Energized Speed Potion')
    event.create('ibpdx:energized_strength_potion').textureThin(0x710857).bucketColor(0x710857).displayName('Energized Strength Potion')
    event.create('ibpdx:energized_health_potion').textureThin(0xCB1C1C).bucketColor(0xCB1C1C).displayName('Energized Health Potion')
    event.create('ibpdx:energized_fire_resistance_potion').textureThin(0xCB6E1C).bucketColor(0xCB6E1C).displayName('Energized Fire Resistance Potion')
	event.create('ibpdx:earthen_blood').textureThick(0x1a1310).bucketColor(0x1a1310).displayName('Earthen Blood')
	event.create('ibpdx:glacial_blood').textureThick(0x43f4f7).bucketColor(0x43f4f7).displayName('Glacial Blood')
	event.create('ibpdx:aethen_blood').textureThick(0xc8da94).bucketColor(0xc8da94).displayName('Aethen Blood')
	event.create('ibpdx:magical_mixture').textureThin(0xDC42FF).bucketColor(0xDC42FF).displayName('Magical Mixture')
	event.create('ibpdx:cooking_oil').textureThin(0x939F46).bucketColor(0x939F46).displayName('Hot Cooking Oil')
	event.create('ibpdx:fake_air').textureThin(0x777777).bucketColor(0x777777).displayName('Hot Air')
	event.create('ibpdx:stock').textureThin(0x999999).bucketColor(0x999999).displayName('Hot Stock')
	event.create('ibpdx:hot_water').textureThin(0x0022BB).bucketColor(0x0022BB).displayName('Hot Water')
	event.create('ibpdx:milk').textureThin(0xEEEEEE).bucketColor(0xEEEEEE).displayName('Hot Milk')
	event.create('ibpdx:liquid_nitric_acid').textureThin(0x748412).bucketColor(0x748412).displayName('Liquid Nitric Acid')
	event.create('ibpdx:liquid_nitrous_acid').textureThin(0x5DE279).bucketColor(0x5DE279).displayName('Liquid Nitrous Acid')
	event.create('ibpdx:seed_oil').textureThin(0xC99A00).bucketColor(0xC99A00).displayName('Seed Oil')
	event.create('ibpdx:molten_bedrock_crystal').textureThick(0x141414).bucketColor(0x141414).displayName('Molten Bedrock Crystal')
	event.create('ibpdx:infinity_fluid').textureThick(0xa794be).bucketColor(0x794be).displayName('Infinity Fluid')
	event.create('ibpdx:molten_uu_matter').textureThick(0x38203d).bucketColor(0x38203d).displayName('Liquid Antimatter')
	event.create('ibpdx:liquid_nitrogen').textureThick(0x0ac9cf).bucketColor(0x0ac9cf).displayName('Liquid Nitrogen')
	event.create('ibpdx:fluid_infinity').textureThick(0xa992bf).bucketColor(0xa992bf).displayName('Fluid Infinity')
	event.create('ibpdx:molten_duskstone').textureThick(0x553e5b).bucketColor(0x553e5b).displayName('Molten Duskstone')
	event.create('ibpdx:nital').textureThick(0x915959).bucketColor(0x915959).displayName('Nital')
	event.create('ibpdx:concentrated_nital').textureThick(0x823939).bucketColor(0x823939).displayName('Concentrated Nital')
	let redstone =  event.create('thermal:redstone').displayName('Destabilized Redstone').textureStill('thermal:block/fluids/redstone_still').textureFlowing('thermal:block/fluids/redstone_flow').bucketColor(0xe30909)
	let glowstone = event.create('thermal:glowstone').displayName('Energized Glowstone').textureStill('thermal:block/fluids/glowstone_still').textureFlowing('thermal:block/fluids/glowstone_flow').bucketColor(0xfcee06).luminosity(15)
})
